favicon: favicon.jpg

menu:
  Home: /
  Photography: /photography
  About: /about

copyright:
  name: Sotiris Karagiannis
  year: 2024
  theme:
    name: ZenSK
    url: https://github.com/sotiriskaragiannis/hexo-theme-zensk
  based_on:
    name: Zen
    url: https://github.com/mouyase/hexo-theme-zen
    author: 某亚瑟
